spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/commerce_shopping_cart"
    username: postgres
    password: 12345
