server:
  port: 0

spring:
  application:
    name: shopping-cart
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smarthome
