spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/cart
    username: cart
    password: cart
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.slf4j: DEBUG
    ru.practicum: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s