server:
  port: 0
spring:
  application:
    name:
      aggregator
  kafka:
    bootstrap-servers: localhost:9092
kafka:
  topics:
    sensor-events: telemetry.sensors.v1
    sensor-snapshot: telemetry.snapshots.v1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/