topic:
  telemetry:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
    aggregator-client-id: OurAggregator
    aggregator-group-id: AggregatorGroupId

kafka:
  bootstrap-servers: localhost:9092
  attempt-timeout: 100
