kafka:
  producer-properties:
    bootstrap.servers: localhost:9092
    key.serializer: org.apache.kafka.common.serialization.VoidSerializer
    value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
  consumer-properties:
    client.id: AggregatorConsumer
    group.id: aggregator-group
    bootstrap.servers: localhost:9092
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
    enable.auto.commit: false
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1