topics:
  sensors: telemetry.sensors.v1
  snapshots: telemetry.snapshots.v1

bootstrap_servers: localhost:9092

producer:
  key_serializer_class: org.apache.kafka.common.serialization.StringSerializer
  value_serializer_class: ru.yandex.practicum.serializer.EventAvroSerializer

consumer:
  client_id: SensorEventConsumer
  group_id: sensorEvent.group_id
  key_deserializer_class: org.apache.kafka.common.serialization.StringDeserializer
  value_deserializer_class: ru.yandex.practicum.deserializer.SensorEventDeserializer
  enable_auto_commit: false