server:
  port: 0
grpc:
  server:
    port: 59091
spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: collector
logging:
  level:
    root: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/