topics:
  sensors: telemetry.sensors.v1
  hubs: telemetry.hubs.v1

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.serializer.EventAvroSerializer
grpc:
  server:
    port: 59091