spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: HubEventConsumer
      group-id: hubEvent.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.deserializer.HubEventDeserializer
      enable-auto-commit: false
      snapshots-client-id: SnapshotsConsumer
      snapshots-group-id: snapshot.group.id
      snapshots-deserializer: ru.yandex.practicum.deserializer.SensorSnapshotDeserializer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      show_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scenario-db
    username: admin
    password: password
grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
topics:
  snapshots-topic: telemetry.snapshots.v1
  hub-event-topic: telemetry.hubs.v1