spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: telemetry_analyzer
  sql:
    init:
      mode: always

kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group:
      hub: telemetry.analyzer.hub
      snapshot: telemetry.analyzer.snapshot
    poll:
      timeout: 100
  topics:
    telemetry-snapshots-v1: telemetry.snapshots.v1
    telemetry-hubs-v1: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
server:
  port: 0

