kafka:
  hub-consumer:
    bootstrap-servers: localhost:9092
    group-id: HubAnalyzerGroup
    client-id: OurAnalyzerForHub
    topics: telemetry.hubs.v1
    attempt-timeout: 2000

  snapshot-consumer:
    bootstrap-servers: localhost:9092
    group-id: AggregatorGroupId
    client-id: OurAnalyzerForSnapshots
    topics: telemetry.snapshots.v1
    attempt-timeout: 500

grpc:
  client:
    hub-router:
      address: 'discovery:///hubRouter'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db-analyzer
    username: test
    password: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/