analyzer:
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      snapshots:
        value-deserializer: ru.practicum.event_deserializer.SensorSnapshotEventAvroDeserializer
      hubs:
        value-deserializer: ru.practicum.event_deserializer.HubEventAvroDeserializer
    hub:
      group-id: hub-events-group
    snapshot:
      group-id: snapshots-group

topic:
  hub-events: telemetry.hubs.v1
  snapshots: telemetry.snapshots.v1

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/analyzer
    username: analyzer
    password: analyzer

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

threadPool:
  arrayBlockingQueue:
    capacity: 2
  corePoolSize: 2
  maximumPoolSize: 2
  keepAliveTime: 60