kafka:
  consumer-hub-properties:
    client.id: HubEventConsumer
    group.id: hub-event-group
    bootstrap.servers: localhost:9092
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
    enable.auto.commit: false
  consumer-snapshot-properties:
    client.id: SnapshotConsumer
    group.id: snapshot-group
    bootstrap.servers: localhost:9092
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotEventDeserializer
    enable.auto.commit: false
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/analyzer"
    username: analyzer
    password: analyzer
