server:
  port: 0
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shopping_store
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Europe/Moscow
        show_sql: false
        type:
          descriptor:
            sql:
              BasicBinder: OFF
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/